### ISSUE TITLE
Bad output and file structure

### ISSUE THREAD

**Issue by Adman** [dobrakmato/messenger-stats#2]
After downloading only messages from facebook, I encountered these issues:

* [main.py L177](https://github.com/dobrakmato/messenger-stats/blob/master/main.py#L177) - html folder does not exist
* [main.py L48](https://github.com/dobrakmato/messenger-stats/blob/master/main.py#L48) - the html is called `index.html` not `index.htm`
* [main.py L62](https://github.com/dobrakmato/messenger-stats/blob/master/main.py#L62) - `messages.html` is located inside `messages` folder
* [statistics.py L179](https://github.com/dobrakmato/messenger-stats/blob/master/statistics.py#L179) - ZeroDivisionError when there are no conversations

Seems that Facebook updated the structure of messages, conversations, html tags etc. For instance my Person Name is `Facebook` and the output shows 0 conversations.

```
Setting: Exclude Group Chats:  True
Setting: Ignore Facebook User:  True
Setting: Exhaustive lists:  False
Parsing profile...
Person name: Facebook
Parsing message index...
Found 0 threads.

Parsed 0 conversations in 5.9604644775390625e-06 seconds
--------------------------------------------------------------
You have exchanged 0 messages total.
You have sent 0 (0%) messages and received 0 (0%) total.
You have exchanged 0 characters in messages total. (0% were sent by you)
You are in 0 conversations.
You talked to 0 different people.
--------------------------------------------------------------
```

**Comment by dobrakmato** [comment]
3

**Comment by dobrakmato** [comment]
I updated the script to work with new FB file structure and fixed problems with encoding of exported JSONs. The script should now work (works on my export).

**Comment by Adman** [comment]
Works now, but the messages/characters sent counter is showing bad results.

```
You have sent 0 (0.0%) messages and received 47684 (100.0%) total. 
You have exchanged 1096632 characters in messages total. (0.0% were sent by you)
```

Also `Most used words by you` field is missing. Looking deeper at the output, almost every field about messages sent by me shows 0.

**Comment by dobrakmato** [comment]
@Adman Have you included **Profile Information** section in you FB export? Exported folder shloud contain file `profile_information/profile_information.json` (https://github.com/dobrakmato/messenger-stats/blob/master/main.py#L51). 

If not, script should ask you at beginning to enter name you use on Facebook (https://github.com/dobrakmato/messenger-stats/blob/master/main.py#L61).

**Comment by Adman** [comment]
@dobrakmato Yes, the downloaded zip file contains profile_information folder along with its json file. The problem may be caused by utf-8 characters in the parsed name `AdriÃ¡n`. Am I right?

**Comment by dobrakmato** [comment]
@Adman You are correct. I totally forgot about fixing encoding in the profile information file.

**Comment by dobrakmato** [comment]
@Adman I just pushed encoding fix to reading profile_information.json too, now it should be able to correctly decode names.

**Comment by Adman** [comment]
@dobrakmato cool, works fine now.
